In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.base import BaseEstimator, ClassifierMixin

class LargestPriorClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self):
        self.largest_class_ = None

    def fit(self, X, y):
        self.largest_class_ = np.argmax(np.bincount(y))

    def predict(self, X):
        return np.full(X.shape[0], self.largest_class_)

classifiers = {
    "Linear Discriminant Analysis": LinearDiscriminantAnalysis(),
    "3-NN": KNeighborsClassifier(n_neighbors=3),
    "Decision Tree": DecisionTreeClassifier(),
    "SVM": SVC(),
    "Bagging": BaggingClassifier(),
    "Random Forest": RandomForestClassifier(),
    "XGBoost": XGBClassifier(),
    "LightGBM": LGBMClassifier(),
    "Largest Prior Classifier": LargestPriorClassifier()
}

def process_dataset(prefix, training_size):
    # Load the feature data and labels
    data_lbp = pd.read_csv(f"{prefix}_DataLBP.csv")
    data_rgb = pd.read_csv(f"{prefix}_DataRGB.csv")
    data_hog = pd.read_csv(f"{prefix}_DataHOG.csv")
    data_h10 = pd.read_csv(f"{prefix}_DataH10.csv")
    labels = pd.read_csv(f"{prefix}_Labels.csv")
    ground_truth = pd.read_csv(f"{prefix}_Results.csv")

    # Combine features (e.g., LBP + RGB)
    features_combined = pd.concat([data_lbp, data_rgb], axis=1)

    # Split data into training and testing sets
    X_train = features_combined.iloc[:training_size]
    X_test = features_combined.iloc[training_size:]
    y_train = labels.iloc[:training_size]
    y_test = labels.iloc[training_size:]

    # Standardize the data
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Train, test, and evaluate the classifiers
    for name, classifier in classifiers.items():
        classifier.fit(X_train_scaled, y_train.values.ravel())
        y_pred = classifier.predict(X_test_scaled)

        print(f"{name}:")
        print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
        print(f"Precision: {precision_score(y_test, y_pred, average='weighted')}")
        print(f"Recall: {recall_score(y_test, y_pred, average='weighted')}")
        print(f"F1-score: {f1_score(y_test, y_pred, average='weighted')}")
        print(f"Confusion matrix:\n{confusion_matrix(y_test, y_pred)}")
        print()

datasets  = [
    ("Pigs_49651_960_540_500f", 2710),
    ("Pigeons_8234_1280_720", 2268),
    ("Pigeons_4927_960_540_600f", 1574),
    ("Pigeons_29033_960_540_300f", 2148),
    ("Koi_5652_952_540", 916),
]

for prefix, training_size in datasets:
    print(f"Processing dataset: {prefix}")
    process_dataset(prefix, training_size)
    print("-" * 50)



Processing dataset: Pigs_49651_960_540_500f
Linear Discriminant Analysis:
Accuracy: 0.3833696667704765
Precision: 0.4359915075830802
Recall: 0.3833696667704765
F1-score: 0.36029685195187444
Confusion matrix:
[[ 18   0   0   0   2   0  42  54   0  27   0   0   0   0  52   0   0   0
    0   0   5   0]
 [  0  65   0   0  15   0   0   0   0   7   0   2   2   0   0   0   0   0
    0   2   0   0]
 [  3   0  65   0   0   0   2  10   0   0   0   0   0   0  22   0   0   0
    0   0  68   0]
 [  0   0   0  13   0  20   0   2   1  11   0  21  16   7   0   0   0  22
    0   7   1   3]
 [  0   1   0   0  12   0   0   0   0   0   0  42   0   0   0   0   0   0
    0   0   0   0]
 [  0  12   0  42   0   4   2   0   1  25  18  33  21  11   0   0   0  22
   11   0   0   0]
 [  0   2   0   0   0   0  59  45   0   0   0   0   0   0   1   0   0   0
    0   0   6   0]
 [  0  12   0   0   0   1  44  70   0   0   0   0   2   0  29   0   0   0
    0   0   2   0]
 [  0  14   0   0   1   1   0   0  17  31  11  3

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Bagging:
Accuracy: 0.2320149486141389
Precision: 0.24563856593667752
Recall: 0.2320149486141389
F1-score: 0.21190978481583028
Confusion matrix:
[[ 10  12   2   8   4   5   6  24   2  21   3  27  11  18   7   0   9   8
    1  16   5   1]
 [  0  42   0   1  15   0   3   0   0   2  18   0   1   6   0   0   2   0
    0   0   3   0]
 [  6   4  31   6   0   0  21   3   1   2   0  17   3   1   4   0  25  16
    0  11  19   0]
 [  0   1  15   0   0  15   3   0   1  22   0  17   2   5   1   0   1  40
    0   1   0   0]
 [  0   2   0   0   5   0   0   0   1  22   4   9   2   0   1   1   1   6
    0   0   0   1]
 [  4  35   4  16   2  22   3   2   2   1  23  28  10  12  11   0   4  21
    2   0   0   0]
 [  0   4   7   0   1   1  45   9   1   3   0   1   0   1   1   0  34   3
    0   0   2   0]
 [ 11  15  11   1   4   2  24  11   4   7   3  16  28   5   4   0   5   3
    1   3   2   0]
 [  1  40   3   5   2   5   0   5   7   8   2  15  21  10   0   1   4   7
    0   0   1   0]
 [  3   5   3   7  

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Linear Discriminant Analysis:
Accuracy: 0.4375545851528384
Precision: 0.5129747318073374
Recall: 0.4375545851528384
F1-score: 0.4227569931902388
Confusion matrix:
[[  6 126  69   9   0  12   0   0   0   0   0   0   0]
 [  1  48 161   3   0   1   0   0   6   0   0   0   0]
 [  0   0 109   9   0   5   0   0  98   0   0   0   1]
 [  9   0  12 147  44   4   0   0   3   1   0   0   0]
 [ 12   8   0   0  81  21   0   0   8   4   0   0   3]
 [  0   0   0   0   0   1   0  12   0   1   0   0   0]
 [  1   0   2   0   3   0  90   0   0  11   3  97   0]
 [ 21   0  53   6  53  28   0  33   2  18   0   0   0]
 [  0   6   1   7   0   0   0   0 104   4   0   0   4]
 [  2   1   7  48  26  30   0   0   0 107   0   1   0]
 [ 19  16   3  37   0  54   0   0   0  21  19   0   0]
 [  0   0   0   0   0   0  43   0   0   1   0 178   0]
 [  7   0   0   0   0   8   0   0   1   0   0   0  79]]

3-NN:
Accuracy: 0.32751091703056767
Precision: 0.43815979774461117
Recall: 0.32751091703056767
F1-score: 0.3245458438755

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Linear Discriminant Analysis:
Accuracy: 0.20430107526881722
Precision: 0.3971306690174346
Recall: 0.20430107526881722
F1-score: 0.22157553517544404
Confusion matrix:
[[  9   0  27   4   0  11   0   0  13   1   5  15   0  35]
 [  0  68   0   0   0   7  46   0   0   0   1   4   3   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  53  16   1  23   2   2  12   1   8  13   1  22]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   3   0   0  18   2  13   0   1   1   4   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  23   2   0   4   2  22   1   1   5   6   0  59]
 [  0   0   3   0   4  67   1   3   0  21   3   4   0  37]
 [  0   0   4   0   1   3   1   0   0  25   0   2   0   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0  97  91  13   0   0   2   7  33  50]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   2   0   0  73  15  34   0   0  16  10   4 101]]

3-NN:


C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Decision Tree:
Accuracy: 0.1313364055299539
Precision: 0.3435195763534678
Recall: 0.1313364055299539
F1-score: 0.16657548899564423
Confusion matrix:
[[ 9  2 11  0  0  3  2 13 40  3  3 12  0 22]
 [ 0 18  6  0 28 16 25  6  0  0  5  9 15  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 4  4 30 11  3 17  2  2 27  0 21 22  4  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  1  2  4  3  3  1  1 10  3  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 11  2  6 11  2 21  7  0  3 39  1 21]
 [ 0  0 18  0  4 16 29  4  5 27  8 11  0 21]
 [ 0  0  1  0  0  1  8  7  0  2 13  2  2  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  9  2  0  9 77 79  6 10  0 20 19 23 39]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12 19  0  8 42 38 18  1  3  5 13 12 84]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM:
Accuracy: 0.1597542242703533
Precision: 0.4214615944692457
Recall: 0.1597542242703533
F1-score: 0.2056437147159802
Confusion matrix:
[[  3   0  54   7   0   1   0   4  13   0  10  12   0  16]
 [  0  52   1   0  32  14  22   0   0   0   0   5   3   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  75  19   3  14   4   1  23   0   9   6   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  19   0   3   2   5   7   0   2   0   0   1   6]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  55   0   0   4   1  23   8   0   1  11   0  22]
 [  0   0   5   0  13  45  33   8   4   8   3   9   0  15]
 [  0   0   4   0   0  13   4   0   0  13   3   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  18   1   0  19 103  52   2  21   0   0  13  29  36]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  16   7   0   3  64  31  16   8   0   1  26   4  79]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Bagging:
Accuracy: 0.1336405529953917
Precision: 0.3324407715054505
Recall: 0.1336405529953917
F1-score: 0.1763010065116597
Confusion matrix:
[[19  1 26  2  2  8  1  7 20  4  8 11  0 11]
 [ 0 58  9  0 15  3 21  6  0  4  4  1  7  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  4 39 10  2 18  6  4 32  0 24  5  0  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  0  0 10  4  6  3  1  2  0  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 51  1  0 12  4 23  2  0  2 19  0 10]
 [ 1  0 15  1  7 29 34 16  5  6  4  7  8 10]
 [ 0  0  5  0  0 13  2  2  0  9  4  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5 16  5  2  5 88 87  9  5  0  6  8 35 23]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 18 18  0  9 53 38 20  9  3  7 25 12 42]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest:
Accuracy: 0.1359447004608295
Precision: 0.4062949603042507
Recall: 0.1359447004608295
F1-score: 0.17567884657739874
Confusion matrix:
[[  6   0  51   0   0   4   0   2  21   0  13   9   0  14]
 [  0  59  12   0  13   5  22   0   0   0   0   5  12   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  66  15   0  24   0   0  13   0  17  10   2   7]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  24   0   0   0   3   3   1   1   0   0   1  12]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  49   1   0  13   0  13   5   0   4  22   0  18]
 [  0   1   4   0   4  40  43   3   5   6   3  16   2  16]
 [  0   0   3   0   0  14   3   0   0  15   1   0   0   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1  34   0   0   1  71 117   4   5   0   2  15  33  11]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  48   7   0   6  53  41   8   1   0   1  26  15  49]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


XGBoost:
Accuracy: 0.1497695852534562
Precision: 0.34058586782916006
Recall: 0.1497695852534562
F1-score: 0.18900168462214645
Confusion matrix:
[[ 6  0 35  0  1  9  0  5 16  0 15 12  1 20]
 [ 0 47 15  0 15  3 37  0  0  0  1  1 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0 65 18  0 15  1  3 18  1 15  7  0  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 14  0  1  1  0 10  1  7  0  0  0 11]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 38  1  0 11  0 33  4  1  0 17  0 20]
 [ 0  2  9  0  5 41 15 12  4 16  6  5 11 17]
 [ 0  0  5  0  0 11  0  0  0 18  2  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [33 15  0  0  3 67 73  6 11  0  2  9 40 35]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3 24  7  0 10 69 31  6  0  1 18 10 17 59]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


LightGBM:
Accuracy: 0.15668202764976957
Precision: 0.34291975549032105
Recall: 0.15668202764976957
F1-score: 0.19419297068672473
Confusion matrix:
[[13  0 28  2  1  8  0  2 20  0 13  5  1 27]
 [ 0 55 13  0 14  3 27  0  0  0  0  4 12  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0 53 16  0 15  1  1 19  1 12 11  3 19]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 18  0  2  0  0  8  3  8  0  1  0  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 31  1  0  6  0 36 18  1  0 11  0 21]
 [ 0  2 14  0  7 37  6 12  3 17  8  5 15 17]
 [ 0  0  2  0  0 11  0  1  0 15  7  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [23  9  0  0  4 82 73  4  4  0  2 11 38 44]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2 48  6  0  9 56 23  2  0  1 29 11 13 55]]

Largest Prior Classifier:
Accuracy: 0.03456221198156682
Precision: 0.0011945464970587612
Recall: 0.03456221198156682
F1-score: 0.0023092791969866475
Confusion matrix:
[[  0   0   0 120   0   0   0   0   0]
 [  0   0   0 1

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Linear Discriminant Analysis:
Accuracy: 0.5973214285714286
Precision: 0.6240411060811386
Recall: 0.5973214285714286
F1-score: 0.5689994691211376
Confusion matrix:
[[ 42   0   0   0  46   1   0   0   0   4   0   0   0   1   0   0   0   0
   11   0]
 [  0 106  18   0   0   0   0   0  20   0   1   1   0   0   0   1   0   2
    0   0]
 [  0   0  48   0   0   2   0  21   7   0   0  31   1   0   0   0   0   0
    1   0]
 [  0   0   7   0   0   0   0  60   1  23   0   0  18   2   0   0   0   0
   19   0]
 [  2   0   0   0 102   6   0   1  14   0   0   0   0   8   0   0   8   0
    6   0]
 [  0   0   0   0   0 126   0   0   3   0   0   0   0   0   0   0   0  20
    0   0]
 [  0   0   0   0   0   0  17   1   0   5 102   0   0   0   4   1  17   0
    1   1]
 [  0   1   2   0   0   0   0 118   0   7   0  10   0   0   0   0   0   0
    0   0]
 [  0   2   0   0   0   1   0   4  65   0   0  16   8   0   0   0   1   2
    0   0]
 [  0   0   1   0   0   0   0  50   9  20   1  14   9   0   0  11   0   

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Decision Tree:
Accuracy: 0.2799107142857143
Precision: 0.32377438584117935
Recall: 0.2799107142857143
F1-score: 0.27744890242387743
Confusion matrix:
[[44  2  0  1  2  1  0  3  1 17  2  4  0  0  0  9  0  6 13  0]
 [ 0 74  7  0  0  0  2  0  5  0  4  3  0  0  0 33  1  3 17  0]
 [ 0  4 37  1  3 10  0 27  3  2  2  3  2  0  0  2  3  2  2  8]
 [ 3  7  9  0  0 39  0  6  0 11  2 14  8  1  0 11 10  0  9  0]
 [43  0 11  0 12  4  0  8  0  0  0  0  2  1  0  0 14  2 47  3]
 [ 0  2  0  0  0 21  0  0  2  2  0  0 30  5 19 31  0 34  0  3]
 [ 1 29 10  1  1  0 12  6 10  2 16  0 11  0  2 27 14  0  4  3]
 [ 0  0  1  0  2 10  0 40 10 28  0  5  0  3  0  6  3 23  6  1]
 [ 0  5  9  1  0  2  0  6 35  1  2 23  1  0  2  3  2  3  0  4]
 [ 3  1  0  0  0  0  0  2 35  9 14 20  0  4  0  1  5 14  7  0]
 [ 3  0  0  0  7  4  0  3  5  5 13  9  1 12  0  0  0  0  3  0]
 [ 3  5  2  4  1 11  0  3  3  4  3 32  8  2  3 31  0  9  0  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  8 11  2  0  1  0  1  0  3

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM:
Accuracy: 0.5508928571428572
Precision: 0.6082917932168942
Recall: 0.5508928571428572
F1-score: 0.5294366538243795
Confusion matrix:
[[ 53   0   0   0   8   0   0   4   0  20   4   0   0   0   0   0   2   0
   14   0]
 [  0 130   0   0   0   1   0   1  13   2   2   0   0   0   0   0   0   0
    0   0]
 [  0   0  43   0   0   8   0   8   4   0   0  44   4   0   0   0   0   0
    0   0]
 [  0   2   4   0   0   0   0  45   3  28   0   0   4   0   0   2  41   0
    0   1]
 [  0   0   0   0  92   4   0  27   1  17   0   0   0   0   0   0   5   0
    1   0]
 [  0   0   0   0   0 126   0   0   0   0   0   0   0   0   0  15   0   2
    0   6]
 [  0   0  17   0   0   0   7   3   0  19  53   0   1   0   2  22  25   0
    0   0]
 [  0   1   4   0   0   0   0  80   0  39   1  13   0   0   0   0   0   0
    0   0]
 [  0  10   1   0   0   5   0   2  48   0   1  30   0   0   0   0   2   0
    0   0]
 [  0   2   0   0   0   0   0   1  45  32  19   2   0   1   0   0  11   0
    0   2]
 [  1   0   

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Bagging:
Accuracy: 0.36026785714285714
Precision: 0.3792824067312948
Recall: 0.36026785714285714
F1-score: 0.3392525508243251
Confusion matrix:
[[ 50  13   2   0   0   0   0   1   0  19   2   0   0   0   0   6   2   1
    9   0]
 [  0 113  14   0   0   0   0   0   2   4   9   1   0   0   0   3   3   0
    0   0]
 [  1   2  42   4   5   9   0  19   1   1   0  15   1   4   0   0   2   1
    2   2]
 [  2   6  14   0   1   1   0  42   0  16   3   0   9   1   0   5  23   1
    6   0]
 [ 46   0   2   4   7  12   0  12   0   1   0   0   5   0   0   0   5   0
   53   0]
 [ 13   0   1   3   4  67   0   3   4   8   0   1   2  13  16   4   0   8
    0   2]
 [  1  13  20   0   1   1   1   4   1   5  61   0   1   0   3  16  10   3
    0   8]
 [  0   0   2   0   5   6   0  39   8  64   0   6   1   0   0   4   0   1
    0   2]
 [  0   3   9   1   2   9   0   2  26   1   8  21   1   0   0   7   3   2
    0   4]
 [  7   2   1   0   0   0   0   0  48  18   3   2   0   0   0   3  27   2
    2   0]
 [  2 

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest:
Accuracy: 0.4870535714285714
Precision: 0.5593297590002457
Recall: 0.4870535714285714
F1-score: 0.45368523595540816
Confusion matrix:
[[ 96   0   0   0   0   0   0   1   0   4   0   0   0   0   0   0   4   0
    0   0]
 [  0 130   3   0   0   0   0   0   8   0   7   1   0   0   0   0   0   0
    0   0]
 [  0   0  42   0   0  13   0  20   4   0   0  28   0   3   1   0   0   0
    0   0]
 [  0   0  12   0   0   0   0  18   4  56   1   0   0   0   0   3  36   0
    0   0]
 [ 77   1   0   0  27  14   0   8   1   5   0   1   0   0   0   0  11   0
    2   0]
 [  0   0   0   0   0 131   0   0   0   0   1   0   0   1   0   6   0   4
    0   6]
 [  0   7   0   0   0   0   1   9   1  15  83   0   0   0   0  23   7   0
    0   3]
 [  0   0   7   0   0   0   0  64   0  58   0   7   0   0   0   0   0   0
    0   2]
 [  0   6   6   0   0  11   0   5  39   0   1  20   1   0   0   1   2   6
    0   1]
 [ 12   5   2   0   0   0   0   0  38   7  33   0   0   0   0   3  13   2
    0   0]
 

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


XGBoost:
Accuracy: 0.4388392857142857
Precision: 0.515645822453736
Recall: 0.4388392857142857
F1-score: 0.4210145811097226
Confusion matrix:
[[ 88   0   0   0   0   0   0   1   0   6   0   0   0   0   0   0   2   0
    8   0]
 [  0 119   4   0   0   2   0   0  11   0   6   6   0   0   0   0   0   1
    0   0]
 [  0   0  41   0   0   7   0  16   0   0   0  43   2   1   1   0   0   0
    0   0]
 [  0   1  15   0   0   0   0  30   2  55   0   0   0   0   0   0  16   0
   10   1]
 [ 39   5   0   0  19   9   0   4  24   8   0   0   1   0   0   0   8   0
   30   0]
 [  0   0   0   0   0 107   0   0   0   0   0   4   4   7   1  14   0  11
    0   1]
 [  6   1   1   0   0   0  15   7   0  28  70   0   0   1   1  14   1   0
    0   4]
 [  0   0   2   0   0   1   0  67   0  38   4   9   1   0   0   3  10   0
    1   2]
 [  0   5   0   0   1   8   0   1  38   2   3  29   2   0   0   0   1   7
    0   2]
 [  7   3   3   0   0   0   1   4  48  20  16   0   0   1   0   0  10   0
    2   0]
 [  1   0

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


LightGBM:
Accuracy: 0.4745535714285714
Precision: 0.5387909060688891
Recall: 0.4745535714285714
F1-score: 0.4551694488144731
Confusion matrix:
[[ 84   0   0   0   0   0   0   0   0   4   0   0   0   0   0   0   2   0
   15   0]
 [  0 124   3   0   1   0   0   0  11   0   2   7   0   0   0   0   0   1
    0   0]
 [  0   0  41   0   0  10   0  18   4   0   0  33   1   3   1   0   0   0
    0   0]
 [  0   0  13   0   0   0   0  29   5  60   0   0   0   0   0   0  21   0
    2   0]
 [ 65   0   0   2  26   9   0   2  13   7   0   0   2   0   0   0   9   0
   12   0]
 [  0   0   0   0   0 109   0   0   0   0   0   2   1   2   0  21   0   8
    0   6]
 [  1   1   0   1   0   0  13   7   1  38  66   0   0   0   0  15   2   0
    0   4]
 [  0   1   3   1   0   0   0  68   0  44   0   7   1   1   0   6   2   0
    3   1]
 [  1   3   1   1   0   8   0   2  42   0   3  27   2   0   0   0   2   6
    0   1]
 [  4   0   2   0   0   0   0   1  51  30  10   0   0   1   0   5   9   0
    1   1]
 [  1  

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Linear Discriminant Analysis:
Accuracy: 0.36908077994428967
Precision: 0.3421718924192163
Recall: 0.36908077994428967
F1-score: 0.3150846344729624
Confusion matrix:
[[  6   0  15   0   1   0   0   0   5]
 [  0  67   0  18  21   0  26   1   9]
 [  7   0   0   0   0  33   0   0  51]
 [  1   4   0   3   1   1  16   2  74]
 [  0  17   0   1   7   3  10   0   2]
 [  1   0   1   0   0  15   0   0   2]
 [  1   2   3   0   0   9  29   0  93]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  12  10   0 138]]

3-NN:
Accuracy: 0.26880222841225626
Precision: 0.3567923884116384
Recall: 0.26880222841225626
F1-score: 0.2758963849708586
Confusion matrix:
[[19  0  3  0  4  1  0  0  0]
 [ 2 76  3  4 17  0 20 11  9]
 [ 0  0  0  4  0 12  0  0 75]
 [ 5  8  0 22  7  0  3  1 56]
 [ 4  2  0  4  7  0  5  0 18]
 [ 2  0  0  0  0  0  0  0 17]
 [17  1  0  1 13  5 19  0 81]
 [ 0  0  0  0  0  0  0  0  0]
 [55  5  0  0 18 13 19  0 50]]

Decision Tree:
Accuracy: 0.22423398328690808
Precision: 0.29884097514

C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-de

SVM:
Accuracy: 0.28133704735376047
Precision: 0.37448944082136454
Recall: 0.28133704735376047
F1-score: 0.2648509113060207
Confusion matrix:
[[ 4  0  0  0  4 19  0  0  0]
 [ 0 47  0  8 29  2 24 29  3]
 [ 0  0  0  0  0 20  0  0 71]
 [ 1  0  0  7  2  4  4  0 84]
 [ 0  0  0  6 28  0  3  0  3]
 [ 0  0  0  0  0 13  0  0  6]
 [20  0  0  2 19  8 24  0 64]
 [ 0  0  0  0  0  0  0  0  0]
 [30  0  0  1 12  8 29  1 79]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Bagging:
Accuracy: 0.298050139275766
Precision: 0.43288524042264304
Recall: 0.298050139275766
F1-score: 0.32726392115855935
Confusion matrix:
[[12  0  1  0  0  5  2  0  7]
 [22 64  6 23  7  2 15  1  2]
 [17  0 12  3  2  7  2  0 48]
 [13  1  0 23  5  0 19  0 41]
 [ 4  2  0  7 12  0 12  0  3]
 [ 5  0  4  2  1  5  1  0  1]
 [ 7  2  1  9 17  6 36  2 57]
 [ 0  0  0  0  0  0  0  0  0]
 [83  0  0 11  0  2 14  0 50]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest:
Accuracy: 0.31058495821727017
Precision: 0.39603932202105085
Recall: 0.31058495821727017
F1-score: 0.3122266550734555
Confusion matrix:
[[14  0  1  0  0  3  0  0  9]
 [ 3 80  0  5 15  0 13 10 16]
 [ 5  0  0  3  0 14  4  0 65]
 [ 6  0  0 12  1  1  7  0 75]
 [ 0  0  0  2 21  0 16  0  1]
 [ 2  0  0  0  0  4  1  0 12]
 [12  0  0  1 18  6 27  0 73]
 [ 0  0  0  0  0  0  0  0  0]
 [69  0  0  4  2  3 17  0 65]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


XGBoost:
Accuracy: 0.32172701949860727
Precision: 0.41885846739546523
Recall: 0.32172701949860727
F1-score: 0.3183370982340551
Confusion matrix:
[[22  0  0  0  1  0  0  0  4]
 [13 47  1  9 14  4 18 29  7]
 [15  0  0  1  3 10  1  0 61]
 [ 8  1  0 33  2  3  9  0 46]
 [ 2  1  0  3 17  0 17  0  0]
 [10  0  0  0  0  2  0  0  7]
 [17  0  0  3 15  2 29  0 71]
 [ 0  0  0  0  0  0  0  0  0]
 [37  0  0  8 11  1 22  0 81]]



C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


LightGBM:
Accuracy: 0.2883008356545961
Precision: 0.37280146871449893
Recall: 0.2883008356545961
F1-score: 0.2845077334114824
Confusion matrix:
[[20  0  0  0  0  0  0  0  7]
 [ 3 48  0 11 12  2 25 35  6]
 [ 8  0  0  7  0 14  1  0 61]
 [ 3  0  0 24  4  8 12  0 51]
 [ 0  0  0  4 12  0 24  0  0]
 [ 9  0  0  0  0  5  0  0  5]
 [16  2  0  5 18  9 21  0 66]
 [ 0  0  0  0  0  0  0  0  0]
 [51  0  0  8  0  0 24  0 77]]

Largest Prior Classifier:
Accuracy: 0.055710306406685235
Precision: 0.0031036382399267544
Recall: 0.055710306406685235
F1-score: 0.005879715715745143
Confusion matrix:
[[  0   0   0   0  27   0   0   0]
 [  0   0   0   0 142   0   0   0]
 [  0   0   0   0  91   0   0   0]
 [  0   0   0   0 102   0   0   0]
 [  0   0   0   0  40   0   0   0]
 [  0   0   0   0  19   0   0   0]
 [  0   0   0   0 137   0   0   0]
 [  0   0   0   0 160   0   0   0]]

--------------------------------------------------


C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ogbon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precisio